---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
  - Scorch13:
    - abbr: GH
      href: https://github.com/scorchmeister13

- Icons:
  - Material Design Icons:
    - abbr: MDI
      href: https://pictogrammers.com/library/mdi/
  - Simple Icons:
    - abbr: SI
      href: https://simpleicons.org/?q=server
  - Selfh.st Icons:
    - abbr: SH
      href: https://selfh.st/icons