# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Scorch's Home Lab
headerStyle: underlined
background:
  image: images/background-01.jpg
  # blur: sm
  brightness: 10
theme: dark
color: stone
cardBlur: md
hideVersion: false
statusStyle: dot
disableCollapse: true
fullWidth: true
layout:
  - Information:
      tab: Information & Services
      icon: si-googlecalendar.svg
      style: row
      columns: 2
  - Media:
      tab: Information & Services
      icon: si-vlcmediaplayer.svg
      style: row
      columns: 4
  - Services:
      tab: Information & Services
      icon: si-docker.svg
      style: row
      columns: 4
      useEqualHeights: true
  - Speedtest:
      tab: Infrastructure
      style: row
      columns: 1
  - DNS:
      tab: Infrastructure
      style: row
      columns: 2
  - Proxmox:
      tab: Infrastructure
      style: row
      columns: 2
  - Hosts:
      tab: Infrastructure
      icon: si-serverfault.svg
      style: row
      columns: 1
      NAS01:
        style: row
        columns: 4
  - Virtual-Machines:
      tab: Infrastructure
      icon: si-serverless.svg
      style: row
      columns: 4
      Node01:
        style: column
      Node02:
        style: column
      Node03:
        style: column
      Node04:
        style: column
