services:
  traefik:
    image: traefik:v3.6.9
    restart: always
    security_opt:
      - apparmor:unconfined
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ={{ timezone }}
      - PORKBUN_API_KEY={{ traefik_porkbun_key }}
      - PORKBUN_SECRET_API_KEY={{ traefik_porkbun_secret }}
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      # INCREASE PROXY TIMEOUTS
      - "--entrypoints.websecure.transport.respondingTimeouts.readTimeout=3600s"
      - "--entrypoints.websecure.transport.respondingTimeouts.writeTimeout=3600s"
      - "--entrypoints.websecure.transport.respondingTimeouts.idleTimeout=3600s"
      # CERTIFICATE RESOLVER      
      - "--certificatesresolvers.letsencrypt.acme.email={{ default_email }}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/acme/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=porkbun"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.delayBeforeCheck=10"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,9.9.9.9:53"
      - "--certificatesresolvers.letsencrypt.acme.keyType=EC256"
      # DASHBOARD
      - "--api.dashboard=true"
      # - "--log.level=DEBUG"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik
      - ./acme:/acme
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # Dashboard Router
      - "traefik.http.routers.traefik.rule=Host(`traefik.{{ inventory_hostname_short.split('-')[-1] }}.{{ domain }}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      # Auth Middleware
      - "traefik.http.middlewares.auth.basicauth.users={{ traefik_auth }}"
      - "traefik.http.routers.traefik.middlewares=auth"
    networks:
      - proxy

networks:
  proxy:
    external: true
