# EmulatorJS per-core options
# emulatorjs:
#   debug: true # Available options will be logged to the browser console
#   cache_limit: null # Cache limit per ROM (in bytes)
#   disable_batch_bootup: false
#   disable_auto_unload: false
#   settings:
#     parallel_n64: # Use the exact core name
#       vsync: disabled
#     snes9x:
#       snes9x_region: ntsc
#     default: # These settings apply to all cores
#       fps: show
#   netplay:
#     enabled: true
#     ice_servers:
#       - urls: "stun:stun.l.google.com:19302"
#       - urls: "stun:stun1.l.google.com:19302"
#       - urls: "stun:stun2.l.google.com:19302"
#       - urls: "turn:openrelay.metered.ca:80"
#         username: "openrelayproject"
#         credential: "openrelayproject"
#       - urls: "turn:openrelay.metered.ca:443"
#         username: "openrelayproject"
#         credential: "openrelayproject" 
#   controls: # https://emulatorjs.org/docs4devs/control-mapping/
#     snes9x:
#       0: # Player 1
#         0: # A MAPPING FOR EACH BUTTON MUST BE SET!
#           value: x # Mapping for keyboard
#           value2: BUTTON_2 # Mapping for connected controller
#       1: # Player 2
#       2: # Player 3
#       3: # Player 4